### ISSUE TITLE
regression: both benchmark 2011/2012 tests fail (QEMU, HiKey, RPi3)

### ISSUE THREAD

**Issue by igoropaniuk** [OP-TEE/optee_test#217] opened 2017-06-22 16:42 UTC
```
root@RPi3:/bin ./xtest -t benchmark 2012

Test ID: 2012
Run test suite with level=0

TEE test application started with device [(null)]
######################################################
#
# benchmark
#
######################################################
 
* benchmark_2012 TEE AES Performance test (TA_AES_CBC)
ERR [171] TEEC:TEEC_InvokeCommand:582: TEE_IOC_INVOKE failed
```

Secure world output:
```
DEBUG:   [0x0] TEE-CORE:tee_ta_init_pseudo_ta_session:259:    Lookup for pseudo TA e626662e-c0e2-485c-b8c8-09fbce6edf3d
DEBUG:   [0x0] TEE-CORE:tee_ta_init_user_ta_session:610: Load user TA e626662e-c0e2-485c-b8c8-09fbce6edf3d
DEBUG:   [0x0] TEE-CORE:ta_load:316: ELF load address 0x40001000
read: Bad address
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:378: tee_ta_close_session(0x8482560)
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:397:    ... Destroy session
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:423:    ... Destroy TA ctx

TEEC_InvokeCommand: 0xffff0000 (orig=2)

```

**Comment by vchong** [comment] 2017-06-23 05:18
Same error on hikey debian :(

```
root@linaro-developer:~# xtest -t benchmark 2011                                                                       
Test ID: 2011                                                                                                          
Run test suite with level=0                                                                                            
                                                                                                                       
TEE test application started with device [(null)]                                                                      
######################################################                                                                 
#                                                                                                                      
# benchmark                                                                                                            
#                                                                                                                      
######################################################                                                                 
                                                                                                                       
* benchmark_2011 TEE AES Performance test (TA_AES_ECB)                                                                 
DEBUG:   [0x0] TEE-CORE:tee_ta_init_pseudo_ta_session:259:    Lookup for pseudo TA e626662e-c0e2-485c-b8c8-09fbce6edf3d
DEBUG:   [0x0] TEE-CORE:tee_ta_init_user_ta_session:610: Load user TA e626662e-c0e2-485c-b8c8-09fbce6edf3d             
DEBUG:   [0x0] TEE-CORE:ta_load:316: ELF load address 0x40001000                                                       
read: Bad address                                                                                                      
ERR [1148] TEEC:TEEC_InvokeCommand:582: TEE_IOC_INVOKE failed                                                          
TEEC_InvokeCommand: 0xffff0000 (orig=2)                                                                                
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:378: tee_ta_close_session(0x3f063de0)                                     
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:397:    ... Destroy session                                               
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:423:    ... Destroy TA ctx                                                
root@linaro-developer:~# xtest -t benchmark 2012                                                                       
Test ID: 2012                                                                                                          
Run test suite with level=0                                                                                            
                                                                                                                       
TEE test application started with device [(null)]                                                                      
######################################################                                                                 
#                                                                                                                      
# benchmark                                                                                                            
#                                                                                                                      
######################################################                                                                 
                                                                                                                       
* benchmark_2012 TEE AES Performance test (TA_AES_CBC)                                                                 
DEBUG:   [0x0] TEE-CORE:tee_ta_init_pseudo_ta_session:259:    Lookup for pseudo TA e626662e-c0e2-485c-b8c8-09fbce6edf3d
DEBUG:   [0x0] TEE-CORE:tee_ta_init_user_ta_session:610: Load user TA e626662e-c0e2-485c-b8c8-09fbce6edf3d             
DEBUG:   [0x0] TEE-CORE:ta_load:316: ELF load address 0x40001000                                                       
read: Bad address                                                                                                      
ERR [1180] TEEC:TEEC_InvokeCommand:582: TEE_IOC_INVOKE failed                                                          
TEEC_InvokeCommand: 0xffff0000 (orig=2)                                                                                
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:378: tee_ta_close_session(0x3f063ca0)                                     
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:397:    ... Destroy session                                               
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:423:    ... Destroy TA ctx                                                
root@linaro-developer:~# 
```

**Comment by igoropaniuk** [comment] 2017-06-23 08:47
the same story in qemu v7

```
* benchmark_2011 TEE AES Performance test (TA_AES_ECB)
read: Bad address
ERR [634] TEEC:TEEC_InvokeCommand:582: TEE_IOC_INVOKE failed
TEEC_InvokeCommand: 0xffff0000 (orig=2)

```

**Comment by etienne-lms** [comment] 2017-06-23 12:33
Issue reproduced on all platforms. It is a regression due to the changes made for AES over SDP perf support.

Fix through P-R https://github.com/OP-TEE/optee_test/pull/218.

**Comment by jbech-optee-adm** [comment] 2017-06-30 09:12
Closing the PR since a fix for it has been merged.

**Closed by jbech-optee-adm** 2017-06-30 09:12 UTC
